name: Publish npm

on:
  # Runs on pushes targeting the next branch
  push:
    branches: ['next']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job
  build:
    if: github.repository_owner == 'icflorescu'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn turbo build
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./package

  # NPM publishing job
  publish:
    if: github.repository_owner == 'icflorescu'
    environment:
      name: npm-registry
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: next
